[theme]
base = "dark"
primaryColor = "#5CE0FF"
backgroundColor = "#070B16"
secondaryBackgroundColor = "#0F1830"
textColor = "#EDF4FF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
headless = true
runOnSave = false
